version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3.7
      - image: circleci/mysql:8.0.16
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ROOT_PASSWORD: root

    steps:
      # Pull the repo
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            # default to composer.lock
            - v1-dependencies-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Update apt cache
      - run:
          name: Update apt cache
          command: sudo apt-get update

      # Activate Xdebug
      - run:
          name: Activate Xdebug
          command: docker-php-ext-enable xdebug

      # Install bcmath
      - run:
          name: Install bcmath
          command: sudo docker-php-ext-install bcmath

      # Install MySQL PDO extension
      - run:
          name: Install MySQL PDO extension
          command: |
            sudo docker-php-ext-install mysqli
            sudo docker-php-ext-install pdo
            sudo docker-php-ext-install pdo_mysql

      # Install our composer dependencies
      - run:
          name: Install Composer Dependencies
          command: composer install -n --prefer-dist

      # Update the CircleCI cache
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.lock" }}
          paths:
            - ./vendor

      # Wait for MySQL to startup
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1

      # Run phpunit
      - run:
          name: Run tests
          command: ./vendor/bin/phpunit --coverage-clover clover.xml

      # Upload clover results to codecov
      - run:
          name: Upload to codecov
          command: bash <(curl -s https://codecov.io/bash)
